# Grafana 数据源自动配置

apiVersion: 1

datasources:
  # Prometheus 数据源
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://go-nomads-prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      timeInterval: "15s"

  # Jaeger 数据源
  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://go-nomads-jaeger:16686
    editable: false
    jsonData:
      tracesToLogs:
        datasourceUid: loki
        filterByTraceID: true
        filterBySpanID: true
