apiVersion: v2
name: go-nomads-infra
description: A Helm chart for Go-Nomads infrastructure services (Redis, RabbitMQ, Elasticsearch, Consul, Zipkin, Prometheus, Grafana)
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - infrastructure
  - redis
  - rabbitmq
  - elasticsearch
  - monitoring
maintainers:
  - name: Go-Nomads Team
    email: team@go-nomads.com
